# Auth Service - Kubernetes Dev Configuration
spring:
  kubernetes:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres-service:5432/auth_service_k8s_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    sql:
      init:
        mode: always