# Shared Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.digital.banking: ${LOG_LEVEL_APP:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/var/log/digital-banking/application.log}
