# API Gateway - Kubernetes Dev Configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  kubernetes:
    discovery:
      enabled: true
